PicHub/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include("mysite.urls")),
    path('admin/', admin.site.urls, name="admin"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# if settings.DEBUG:
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

from . import views


urlpatterns = [
    # Ссылка на главную страницу
    path('', views.index, name="index"),
    # Использование встроенных ссылок авторизации
    path('account/', include('django.contrib.auth.urls')),
    #Ссылка на страницу проекта
    path('register/', views.register, name="register"),
    #Ссылка на сраницу авторизации
    path('account/login', views.account_redirect, name='account_redirect'),
    # Ссылка на страницу профиля пользователя
    path('<str:name>', views.profile, name="profile"),
    # Ссылка на странцу редактирования профиля
    path('edit_profile/', views.edit_profile, name="editprofile"),
    # Ссылка для подписок
    path('follow/<str:username>/', views.follow, name='follow'),
    # Ссылка для отписок
    path('unfollow/<str:username>/', views.unfollow, name='unfollow'),
    # Ссылка на сраницу подписчиков и друзей
    path('followers/', views.followers, name='followers'),
    # Ссылка на страницу создания проека
    path('create_project/', views.create_project, name='create_project'),
    # Ссылка загрузки фотографий при создании проекта
    # path('create_project/upload_images/', views.upload_image)
    # Ссылка на страницу понравившихся проектов
    path('liked_projects/' , views.liked_projects, name='liked_projects'),
    # Ссылка на страницу подписок пользователя
    path('follows/', views.follows, name='follows'),
    # Ссылка на страницу понравившихся проектов
    path('pined_projects/' , views.pined, name='pined'),
    # Ссылка на страницу настраивания проекта
    # path('<str:autor>/<str:projectname>/settings', views.create_project, name='project_settings'),
    # Ссылка для закрепления проекта
    # path('pinproj/<str:autor>/<str:name>/', views.pin, name="pin_proj"),
    # Ссылка для открепления проекта
    # path('unpinproj/<str:autor>/<str:name>/', views.unpin, name="unpin_proj"),
    # Ссылка лайк проекта
    # path('like_proj/<str:autor>/<str:name>/', views.like, name="like_proj"),
    # Ссылка дизлайк проекта
    # path('unlike_proj/<str:autor>/<str:name>/', views.unlike, name="unlike_proj"),
    # ajax на странице проекта
    path('project_ajax/', views.project_ajax),
    # Удаление комментария на странице проекта
    path('delete_review/', views.delete_review, name="delete_review"),
    # Ссылка на поиск пользователей
    path('search_users/', views.search_users, name="search_users"),
    # Обработка прочтения всех уведомлений пользователя
    path('check_notifications/', views.check_notifications),
    # Ссылка на страницу со всеми проектами
    path('main/', views.main_page, name="main"),
    # Ссылка на добавление достижений
    path('addachievements/', views.addachievements, name="addachievements"),
    # Ссылка на ajax удаление файла с проекта
    path('delete_file/', views.delete_file),
    # Ссылка на страницу проекта
    path('<str:autor>/<str:projectname>/', views.project, name='project'),
    # Ссылка на страницу файлов проекта
    path('<str:autor>/<str:projectname>/files/',views.project_files, name="project_files"),
    # Ссылка на страницу редактирования проекта
    path("<str:autor>/<str:projectname>/settings/edit/", views.project_settings_edit, name="settings_proj"),
    # Ссылка на страницу удаления проекта
    path("<str:autor>/<str:projectname>/settings/delete/", views.project_settings_delete, name="settings_proj_delete"),
    # Ссылка на страницу добавления файлов
    path("<str:autor>/<str:projectname>/settings/addfiles/", views.project_settings_addfiles, name="settings_proj_addfiles"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("mysite.urls"))
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mysite/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.utils.timezone import localdate, now


AUTH_USER_MODEL = getattr(settings, 'AUTH_USER_MODEL', 'auth.User')


class Achievement(models.Model):
    """Модель достижения"""
    image = models.ImageField(upload_to='userachievements/')
    uploaded_at = models.DateTimeField(default=now)
    
    class Meta:
        verbose_name = "достижение"
        verbose_name_plural = "Достижения"
        

class Notification(models.Model):
    """Модель уведомления"""
    TYPES = (
        (0, "like_project"),
        (1, "like_comment"),
        (2, "follow"),
        (3, "delete_comment")
    )
    text = models.CharField("Текст уведомления", max_length=200)
    type = models.CharField("Тип уведомления", choices=TYPES, max_length=30, default=0)
    date = models.DateTimeField("Время", default=now)
    autor = models.ForeignKey(User, on_delete=models.PROTECT, null=True)
    obj_id = models.IntegerField("id обьекта уведомления", null=False, default=0)
    obj_title = models.CharField("Имя обьекта уведомления", max_length=100, default="")
    is_check = models.BooleanField("Просмотрено", default=False)

    class Meta:
        verbose_name = 'уведомление'
        verbose_name_plural = 'Уведомления'


class Comment(models.Model):
    """Модель комментария"""
    autor = models.ForeignKey(User, on_delete=models.PROTECT, related_name="comments")
    text = models.TextField("Комментарии", max_length=2000)
    data = models.DateField(default=localdate)
    liked_users = models.ManyToManyField(User, blank=True)
    
    class Meta:
        verbose_name = 'комментарий'
        verbose_name_plural = 'Комментарии'


class UploadedFile(models.Model):
    """Модель загружаемого файла"""
    file = models.ImageField(upload_to='usersprojects/')
    uploaded_at = models.DateTimeField(default=now)

    def __str__(self):
        return f"file_{self.id}"
    
    class Meta:
        verbose_name = 'файл'
        verbose_name_plural = 'Файлы'


class Project(models.Model):
    """Модель проекта (репозитория)"""
    autor = models.ForeignKey(User, on_delete=models.PROTECT, related_name="projects")
    name = models.CharField("Название проекта", max_length=100, blank=False)
    is_private = models.BooleanField("Приватный", default=False)
    is_pinned = models.BooleanField("Закрепленный", default=False)
    created_date = models.DateField(default=localdate)
    description = models.TextField("Описание проекта", blank=True)
    comments = models.ManyToManyField(Comment, related_name='project', blank=True)
    collaborators = models.ManyToManyField(User, related_name='collaborators', blank=True)
    likes = models.ManyToManyField(User, blank=True, related_name="liked_projects")
    files = models.ManyToManyField(UploadedFile, blank=True)
    # current_id = models.IntegerField("Основной файл", default=0)

    # Имя для пути к файлу
    # slug = models.SlugField(unique=True, default=slugify(name))
    
    # def save(self, *args, **kwargs):
    #     """Метод сохранения экземпляра"""
    #     if not self.slug:
    #         self.slug = slugify(self.name)
    #     return super().save(*args, **kwargs)
    
    class Meta:
        # ! unique_together для того чтобы уникальность была для отдельного пользователя 
        # ! (у одного пользователя не может быть проектов с одинаковыми названиями)
        # unique_together = 'autor', 'slug'
        # ! Отображение в базе данных
        verbose_name = 'проект'
        verbose_name_plural = 'Проекты'


class Profile(models.Model):
    """Модель профиля пользователя"""
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="profile", default=None, null=True)
    name = models.CharField("Имя", max_length=100, default="User", null=True, blank=True)
    telegram = models.CharField("Телеграм", max_length=50, blank=True, null=True, default="")
    register_date = models.DateField(default=localdate)
    photo = models.ImageField("Фото профиля", null=True, blank=True, upload_to="usersphotos/", 
                              default='usersphotos/default.png')
    age = models.IntegerField("Возраст", default=18)
    organization = models.CharField("Организация", max_length=100,
                                     default="Самозанятый")
    followers = models.ManyToManyField(User, related_name='following')
    notifications = models.ManyToManyField(Notification)
    is_check_notification = models.BooleanField("Чтение комментариев", default=True)
    achievements = models.ManyToManyField(Achievement)
    
    # liked_projects = models.ManyToManyField(Project, related_name="likedprojects")

    def __str__(self):
        return self.user.username
    
    class Meta:
        verbose_name = 'профиль'
        verbose_name_plural = 'Профили'
    
    def is_friend(self, other: User):
        other_followers = Profile.objects.get(user=other).followers.all()
        if other in self.followers.all() and self.user in other_followers:
            return True
        return False

    def is_follower(self, other: User):
        if other in self.followers.all():
            return True
        return False


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance, name=instance.username)

mysite/templates/add_achievements.html
{% extends "base.html" %}

{% load static %}

{% block title %}PicHub{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/addachievements.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script
    src="https://code.jquery.com/jquery-3.6.0.min.js"
    integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
    crossorigin="anonymous"></script>
{% endblock %}

{% block content %}
    <div class="add_achievements_block">
        <h1>Добавьте достижения</h1>
        <form action="" method="POST" enctype="multipart/form-data">
            <p class="sucsess_text none">Файлы успешно добавлены!</p>
            {% csrf_token %}
            {{ add_achievements_form.achievements }}
            <input type="submit" value="Добавить">
        </form>
    </div>
    <script>
        // Появление текста об успешном добавлении файлов 
        $("#id_achievements").change(() => {
            $(".sucsess_text").removeClass("none");
        });
    </script>
{% endblock %}

mysite/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>{% block title %}{% endblock %}</title>

  <!-- Подключаем шрифт -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Jost:ital,wght@0,100..900;1,100..900&display=swap"
    rel="stylesheet">

  <link rel="website icon" href="{% static "img/site_img/base/logo.png" %}">
  <script src="https://kit.fontawesome.com/920a23c733.js" crossorigin="anonymous"></script>
  {% block head %}{% endblock %}
  <link rel="stylesheet" href="{% static 'css/style.css' %}" />
  <!-- Подключаем ajax -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</head>

<body>
  <section class="navigation">
    <div class="header_of_train">
      <a href="{% url 'profile' user.username %}">
        <img class="" src="/media/{{ user.profile.photo }}">

        <!-- <img src="{% static 'img/site_img/base/logo.png' %}" alt=""> -->
      </a>
      <a id="close_btn"><img src="{% static 'img/site_img/base/close.png' %}" alt=""></a>
    </div>
    <hr class="nav_sep">
    {% if user.is_superuser %}
    <a class="navlink" href="/admin">
      <!-- <i class="fa-solid fa-user-tie"></i> -->
      <i class="fa-solid fa-address-card"></i>
      Администрирование
    </a>
    {% endif %}
    <a class="navlink" href="{% url 'main' %}">
      <i class="fa-solid fa-house"></i>
      Главная
    </a>
    <a class="navlink" href="{% url 'profile' user.username %}">
      <i class="fa-solid fa-user"></i>
      Профиль
    </a>
    <div class="navlink">
      <i class="fa-solid fa-right-from-bracket"></i>
      <form action="{% url 'logout' %}" method="post" class="leave_form">
        {% csrf_token %}
        <button type="submit" href="{% url 'logout' %}" class="logout_btn">
          Выйти
        </button>
      </form>
    </div>
    <hr class="nav_sep">
    <a class="navlink" href="{% url 'followers' %}">
      <i class="fa-solid fa-user-group"></i>
      Друзья
    </a>
    {% comment %} <a class="navlink" href="{% url 'follows' %}">
      <i class="fa-solid fa-user-plus"></i>
      Подписки
    </a> {% endcomment %}
    <a class="navlink" href="{% url 'liked_projects' %}">
      <i class="fa-solid fa-heart"></i>
      Понравившиеся
    </a>
    <a class="navlink" href="{% url 'pined' %}">
      <i class="fa-solid fa-bookmark"></i>
      Избранное
    </a>
    <hr class="nav_sep">
    <a class="navlink" href="{% url 'create_project' %}">
      <i class="fa-regular fa-square-plus"></i>
      Создать проект
    </a>

    <a class="navlink" href="{% url 'editprofile' %}">
      <i class="fa-solid fa-user-pen"></i>
      Изменить профиль
    </a>

    <a class="navlink" href="{% url 'addachievements' %}">
      <i class="fa-solid fa-star"></i>
      Добавить достижения
    </a>
    <hr class="nav_sep">
  </section>
  <div class="profile_info">
    <h4>Уведомления:</h2>
      <div class="all_notifications">
        {% for notif in user.profile.notifications.all reversed %}
        {% include "blocks/notification.html" %}
        {% endfor %}
      </div>
      <a id="check_notification_btn">Прочитать все</a>
  </div>
  {% block modals_window %}
  {% endblock %}
  <section class="main" id="main">
    <header>
      <nav>
        <div class="left">
          <a id="but">
            <div>
              <!-- <i class="fa-solid fa-compass"></i> -->
              <!-- <i class="fa-solid fa-ellipsis"></i> -->
              <i class="fa-solid fa-bars"></i>
            </div>
            <!-- <img src="{% static 'img/site_img/base/menu.png' %}" alt=""> -->
          </a>
          <a href="{% url 'main' %}"><img src="{% static 'img/site_img/base/logo.png' %}" alt=""></a>
          <a href="{% url 'profile' user.username %}">
            <h3 class='title'>{{ user.username }}</h3>
          </a>
        </div>
        <div class="right">
          <a class="center-link" id="prof">
            {% if not user.profile.is_check_notification %}
            <div class="image_notification image_check">

            </div>
            {% endif %}
            <div class="header_img">
              <i class="fa-solid fa-bell"></i>
            </div>
          </a>
        </div>
      </nav>
    </header>

    {% block content %}{% endblock %}

    <footer>
      <img src="{% static "img/site_img/base/message_love.png" %}" alt="" class="message_love">
      <img src="{% static "img/site_img/base/planet.png" %}" alt="" class="planet">
      <img src="{% static "img/site_img/base/computer.png" %}" class="computer">
    </footer>
  </section>
  <script>
    // Отправка запросов на обновление уведомлений
    // updateNotification = function () {
    //   // $.get('/get_notifications/{{ user.username }}/', function (data) {

    //   // });
    //   console.log("kjj");
    // };
    // setInterval(5, updateNotification());

    $(document).ready(function () {
      // Обработка прочтения уведомлений на странице
      $('#check_notification_btn').on("click", function (event) {
        event.preventDefault();
        $.ajax({
          url: "/check_notifications/",
          type: "POST",
          data: {
            'csrfmiddlewaretoken': '{{ csrf_token }}'
          },
          success: function (response) {
            $(".profile_info .check_lamp").removeClass("lamp");
            $("#prof .image_check").removeClass("image_notification");
          }
        });
      });
    });
  </script>
</body>

<!-- Подключаем скрипт всплывающего меню -->
<script src="{% static 'js/train.js' %}"></script>
<!-- Подключаем скрипт всплывающего меню профиля -->
<script src="{% static 'js/profile_menu.js' %}"></script>
<!-- Подключаем скрипт задателя высоты для footer -->
<!-- <script src="{% static 'js/changefooterheight.js' %}"></script> -->

</html>

mysite/templates/edit_profile.html
{% extends 'base.html' %}
{% load static%}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/edit_profile.css' %}">
{% endblock %}

{% block title %}PicHub{% endblock %}

{% block content %}
<main>
    <form class="text_form" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <section class="foto">
            <article>
                <img src="/media/{{ request.user.profile.photo }}" alt="">
                <p class="username">{{ user.username }}</p>
                {% comment %} <p class="sub">Подписчики</p> {% endcomment %}
                
                {{ profileform.photo.as_widget }}
                {% comment %} <button type="button">Изменить фото профиля</button> {% endcomment %}
            </article>
        </section>
        {% comment %} <section class="strip"></section> {% endcomment %}

        <section class="information-about-me">
            <article>
                <div class="block-inform">
                    <h3>Как к вам обращаться? <img src="{% static "img/site_img/base/pen_and_paper.png" %}" alt=""></h3>
                    {{ profileform.name.as_text }}
                </div>

                <div class="block-inform midle-block">
                    <h3>Телеграм <img src="{% static "img/site_img/base/pen_and_paper.png" %}" alt=""></h3>
                    {{ profileform.telegram.as_text }}
                </div>

                <div class="block-inform">
                    <h3>Организация <img src="{% static "img/site_img/base/pen_and_paper.png" %}" alt=""></h3>
                    {{ profileform.organization.as_text }}
                </div>

                <button type="submit">Сохранить изменения</button>
            </article>
        </section>
    </form>
</main>

<div class="circle">
    <span class="left-top"></span>
    <span class="right-top"></span>
    <span class="left-bottom"></span>
    <span class="right-bottom"></span>
</div>

{% endblock %}

mysite/templates/error.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Ошибка{% endblock %}

{% block content %}

{% if code == 403 %}
    <img class='error403' src="{% static 'img/site_img/errors/error403.png' %}" alt="">
{% endif %}

<h2 class="error">
    {{ error }}
</h2> 
{% endblock %}

mysite/templates/followers.html
{% extends 'base.html' %}
{% load static %}

{% block title %}PicHub{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/followers.css' %}">
{% endblock %}

{% block content %}
<main>
    <div class="followers_nav">
        <a href="{% url 'followers' %}" class="{% if title == "Ваши подписчики и друзья:" %} current_nav {% endif %}">
            <i class="fa-solid fa-user-group"></i>
            Друзья и подписчики
        </a>
        <a href="{% url 'follows' %}" class="{% if title == "Ваши подписки:" %} current_nav {% endif %}">
            <i class="fa-solid fa-user-plus"></i>
            Подписки
        </a>
        <a href="{% url 'search_users' %}" class="{% if title == "" %} current_nav {% endif %}">
            <i class="fa-solid fa-magnifying-glass"></i>
            Поиск
        </a>
    </div>

    {% if search_form %}
        <h3>Поиск пользователей</h3>
        <form action="" method="POST" class="search_form">
            {% csrf_token %}
            {{ search_form.username }}
            <input type="submit" value="Искать">
        </form>
    {% endif %}

    <section class="friends">
        <h3>{{ title }}
            {% if title %}
                ({{ followers|length }})
            {% endif %}
        </h3>
        {% if followers|length > 0 %}
            {% for follower in followers %}
            <article class="already-friends">
                <a class="midle" href="{% url 'profile' follower.follower.username %}">
                    <img src="/media/{{ follower.follower.profile.photo }}" alt="">
                </a>
                <a class="midle">{{ follower.follower.username }}</a>
                {% if follower.status == "Подписчик" %}
                    <a class="status follower">{{ follower.status }}</a>
                {% elif follower.status == "Подписки" %}
                    <a class="status follower">{{ follower.status }}</a>
                {% elif follower.status == "Друзья" %}
                    <a class="status friend">{{ follower.status }}</a>
                {% endif %}
            </article>
            {% endfor %}
        {% else %}
            <h3 class="noresult">{{ searchstatus }}</h3>
        {% endif %}
    </section>
</main>
{% endblock %}

mysite/templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static "css/index.css" %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Jost:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Nosifer&display=swap" rel="stylesheet">
    <link rel="website icon" href="{% static "img/site_img/base/logo.png" %}">
    
    <title>PicHub</title>
</head>
<body>
    <header>
        <ul class="left-header-ul">
            {% comment %} <li class="one"></li>
            <li class="options left-li2"><a href=""></a></li>
            <li class="options left-li3"><a href=""></a></li>
            <li class="options left-li4"><a href=""></a></li>
            <li class="options left-li5"><a href=""></a></li>
            <li class="options left-li6"><a href=""></a></li>
            <li class="options left-li7"><a href=""></a></li> {% endcomment %}
        </ul>

        <ul class="right-header-ul">
            {% comment %} <li class="search"><input type="text" placeholder="Поиск"></li> {% endcomment %}
            <li class="log-in"><a href="{% url 'login' %}">Войти</a></li>
            <li class="sign-in"><a href="{% url 'register' %}">Заргестрироваться</a></li>
        </ul>
    </header>

    

    <main>
        <section class="main-text">
            <p>P<span class="grad-i">I</span>CHU<span class="grad-b">B</span></p>
        </section>

        <section class="registration-main">
            {% comment %} <form action="">
                <p>Адрес электронной почты</p>
                <div>
                    <input type="email" placeholder="you@company.com">
                    <button>Зарегестрируйтесь на PicHub</button>
                </div>
            </form> {% endcomment %}

        </section>

        <section class="possibilities">
            <div class="left-text1">
                <div class="first-vertycal"></div>
                <p>Наш сайт предоставляет возможности</p>
            </div>

            <div class="left-text2">
                <div class="circle_text">
                    <div></div>
                    <p>Сохранить свои проекты</p>
                </div>
                <div class="last-strip"></div>
            </div>

            <div class="left-text2">
                <div class="circle_text">
                    <div></div>
                    <p>Просматривать другие работы</p>
                </div>
                <div class="last-strip"></div>
            </div>

            <div class="left-text2">
                <div class="circle_text">
                    <div></div>
                    <p>Взаимодействовать с другими пользователями</p>
                </div>
                <div class="last-strip"></div>
            </div>

            <div class="left-text2">
                <div class="circle_text">
                    <div></div>
                    <p>Сохранять проекты других авторов</p>
                </div>
                <div class="last-strip"></div>
            </div>


            <div class="left-text2">
                <div class="circle_text">
                    <div></div>
                    <p>Искать необходимые проекты</p>
                </div>
            </div>
        </section>

    </main>

    <div class="figure">
        <span class="low-pink-circle"></span>
        <span class="pink-circle"></span>
        <span class="purple-circle"></span>
        <span class="bottom-pink-circle"></span>
        <span class="low-purple-circle1"></span>
        <span class="low-purple-circle2"></span>
        <span class="right-pink-circle"></span>
        <span class="right-purple-circle"></span>
        <span class="low-right-pink-circle"></span>
        <span class="medium-purple-circle"></span>
        <span class="medium-pink-circle"></span>

        <img src="{% static "img/site_img/index/small-camera.png" %}" alt="" class="small-camera">
        <img src="{% static "img/site_img/index/paper.png" %}" alt="" class="paper">
        <img src="{% static "img/site_img/index/program.png" %}" alt="" class="program">
        <img src="{% static "img/site_img/index/camera.png" %}" alt="" class="camera">
        <img src="{% static "img/site_img/index/love.png" %}" alt="" class="love">
        <img src="{% static "img/site_img/index/backpack.png" %}" alt="" class="backpack">
        <img src="{% static "img/site_img/index/board.png" %}" alt="" class="board">
        <img src="{% static "img/site_img/index/computer.png" %}" alt="" class="computer">
        <img src="{% static "img/site_img/index/cup.png" %}" alt="" class="cup">
        <img src="{% static "img/site_img/index/head.png" %}" alt="" class="head">
        <img src="{% static "img/site_img/index/microscope.png" %}" alt="" class="microscope">
        <img src="{% static "img/site_img/index/planet.png" %}" alt="" class="planet">
        <img src="{% static "img/site_img/index/phone.png" %}" alt="" class="phone">
    </div>
   

    <footer>
        <section>
            <span class="support">Support PicHub</span>
            <img src="{% static "img/site_img/index/big_planet.png" %}" alt="" class="big_planet">
            <span class="mail">PicHub@gmail.com</span> 
        </section>
    </footer>
</body>
</html>

mysite/templates/main.html
{% extends 'base.html' %}
{% load static %}

{% block title %}PicHub{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/like_project.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
{% endblock %}

{% block content %}
<main>
    <div class="search_block">
        <h3 class="zag">{{ main_title }}
            {% if not filter_form %}
                <a href="{% url 'main' %}" class="reset_search"><i class="fa-solid fa-house"></i> На главную</a>
            {% endif %}
        </h3>
        {% if search_form %}
            <div class="hidden_search">
                <a id="show_search" class="show_search"><i class="fa-solid fa-magnifying-glass"></i></a>
                <form action="" method="POST" class="search_form">
                    {% csrf_token %}
                    {{ search_form.name }}
                    <input type="submit" value="Искать">
                </form>
            </div>
        {% endif %}
        </div>
    {% comment %} {% if filter_form %}
    <form method="POST" class="filter_form">
        {% csrf_token %}
        {{ filter_form.filter }}
        <input type="submit" value="Фильтровать">
    </form>
    {% endif %} {% endcomment %}
    <section class="projects" id="project_list">
        {% include "blocks/all_projects.html" %}
    </section>
    {% if search_form %}
    <div class="load_block">
        <a id="lazy_more">Загрузить еще</a>
    </div>
    {% endif %}
    <script>
        // Скрипт для динамической загрузки проектов в виде пагинатора
        var page = 1;
        var empty_page = false;
        var block_request = false;

        $('#lazy_more').click(function (e) {
            e.preventDefault();
            if (empty_page === false && block_request === false) {
                block_request = true;
                page += 1;
                if (page == {{ max_pages }}){
                    $('#lazy_more').remove();
                }
                $.get('?page=' + page, function (data) {
                    if (data === '') {
                        empty_page = true;
                        console.log("1");
                    } else {
                        block_request = false;
                        $('#project_list').append(data);
                    }
                });
            }
        });
    </script>
    <script src="{% static 'js/hide_search.js' %}"></script>
</main>
{% endblock %}