PicHub/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include("mysite.urls")),
    path('admin/', admin.site.urls, name="admin"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# if settings.DEBUG:
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

from . import views


urlpatterns = [
    # Ссылка на главную страницу
    path('', views.index, name="index"),
    # Использование встроенных ссылок авторизации
    path('account/', include('django.contrib.auth.urls')),
    #Ссылка на страницу проекта
    path('register/', views.register, name="register"),
    #Ссылка на сраницу авторизации
    path('account/login', views.account_redirect, name='account_redirect'),
    # Ссылка на страницу профиля пользователя
    path('<str:name>', views.profile, name="profile"),
    # Ссылка на странцу редактирования профиля
    path('edit_profile/', views.edit_profile, name="editprofile"),
    # Ссылка для подписок
    path('follow/<str:username>/', views.follow, name='follow'),
    # Ссылка для отписок
    path('unfollow/<str:username>/', views.unfollow, name='unfollow'),
    # Ссылка на сраницу подписчиков и друзей
    path('followers/', views.followers, name='followers'),
    # Ссылка на страницу создания проека
    path('create_project/', views.create_project, name='create_project'),
    # Ссылка загрузки фотографий при создании проекта
    # path('create_project/upload_images/', views.upload_image)
    # Ссылка на страницу понравившихся проектов
    path('liked_projects/' , views.liked_projects, name='liked_projects'),
    # Ссылка на страницу подписок пользователя
    path('follows/', views.follows, name='follows'),
    # Ссылка на страницу понравившихся проектов
    path('pined_projects/' , views.pined, name='pined'),
    # Ссылка на страницу настраивания проекта
    # path('<str:autor>/<str:projectname>/settings', views.create_project, name='project_settings'),
    # Ссылка для закрепления проекта
    # path('pinproj/<str:autor>/<str:name>/', views.pin, name="pin_proj"),
    # Ссылка для открепления проекта
    # path('unpinproj/<str:autor>/<str:name>/', views.unpin, name="unpin_proj"),
    # Ссылка лайк проекта
    # path('like_proj/<str:autor>/<str:name>/', views.like, name="like_proj"),
    # Ссылка дизлайк проекта
    # path('unlike_proj/<str:autor>/<str:name>/', views.unlike, name="unlike_proj"),
    # ajax на странице проекта
    path('project_ajax/', views.project_ajax),
    # Удаление комментария на странице проекта
    path('delete_review/', views.delete_review, name="delete_review"),
    # Ссылка на поиск пользователей
    path('search_users/', views.search_users, name="search_users"),
    # Обработка прочтения всех уведомлений пользователя
    path('check_notifications/', views.check_notifications),
    # Ссылка на страницу со всеми проектами
    path('main/', views.main_page, name="main"),
    # Ссылка на добавление достижений
    path('addachievements/', views.addachievements, name="addachievements"),
    # Ссылка на ajax удаление файла с проекта
    path('delete_file/', views.delete_file),
    # Ссылка на страницу проекта
    path('<str:autor>/<str:projectname>/', views.project, name='project'),
    # Ссылка на страницу файлов проекта
    path('<str:autor>/<str:projectname>/files/',views.project_files, name="project_files"),
    # Ссылка на страницу редактирования проекта
    path("<str:autor>/<str:projectname>/settings/edit/", views.project_settings_edit, name="settings_proj"),
    # Ссылка на страницу удаления проекта
    path("<str:autor>/<str:projectname>/settings/delete/", views.project_settings_delete, name="settings_proj_delete"),
    # Ссылка на страницу добавления файлов
    path("<str:autor>/<str:projectname>/settings/addfiles/", views.project_settings_addfiles, name="settings_proj_addfiles"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("mysite.urls"))
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mysite/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.utils.timezone import localdate, now


AUTH_USER_MODEL = getattr(settings, 'AUTH_USER_MODEL', 'auth.User')


class Achievement(models.Model):
    """Модель достижения"""
    image = models.ImageField(upload_to='userachievements/')
    uploaded_at = models.DateTimeField(default=now)
    
    class Meta:
        verbose_name = "достижение"
        verbose_name_plural = "Достижения"
        

class Notification(models.Model):
    """Модель уведомления"""
    TYPES = (
        (0, "like_project"),
        (1, "like_comment"),
        (2, "follow"),
        (3, "delete_comment")
    )
    text = models.CharField("Текст уведомления", max_length=200)
    type = models.CharField("Тип уведомления", choices=TYPES, max_length=30, default=0)
    date = models.DateTimeField("Время", default=now)
    autor = models.ForeignKey(User, on_delete=models.PROTECT, null=True)
    obj_id = models.IntegerField("id обьекта уведомления", null=False, default=0)
    obj_title = models.CharField("Имя обьекта уведомления", max_length=100, default="")
    is_check = models.BooleanField("Просмотрено", default=False)

    class Meta:
        verbose_name = 'уведомление'
        verbose_name_plural = 'Уведомления'


class Comment(models.Model):
    """Модель комментария"""
    autor = models.ForeignKey(User, on_delete=models.PROTECT, related_name="comments")
    text = models.TextField("Комментарии", max_length=2000)
    data = models.DateField(default=localdate)
    liked_users = models.ManyToManyField(User, blank=True)
    
    class Meta:
        verbose_name = 'комментарий'
        verbose_name_plural = 'Комментарии'


class UploadedFile(models.Model):
    """Модель загружаемого файла"""
    file = models.ImageField(upload_to='usersprojects/')
    uploaded_at = models.DateTimeField(default=now)

    def __str__(self):
        return f"file_{self.id}"
    
    class Meta:
        verbose_name = 'файл'
        verbose_name_plural = 'Файлы'


class Project(models.Model):
    """Модель проекта (репозитория)"""
    autor = models.ForeignKey(User, on_delete=models.PROTECT, related_name="projects")
    name = models.CharField("Название проекта", max_length=100, blank=False)
    is_private = models.BooleanField("Приватный", default=False)
    is_pinned = models.BooleanField("Закрепленный", default=False)
    created_date = models.DateField(default=localdate)
    description = models.TextField("Описание проекта", blank=True)
    comments = models.ManyToManyField(Comment, related_name='project', blank=True)
    collaborators = models.ManyToManyField(User, related_name='collaborators', blank=True)
    likes = models.ManyToManyField(User, blank=True, related_name="liked_projects")
    files = models.ManyToManyField(UploadedFile, blank=True)
    # current_id = models.IntegerField("Основной файл", default=0)

    # Имя для пути к файлу
    # slug = models.SlugField(unique=True, default=slugify(name))
    
    # def save(self, *args, **kwargs):
    #     """Метод сохранения экземпляра"""
    #     if not self.slug:
    #         self.slug = slugify(self.name)
    #     return super().save(*args, **kwargs)
    
    class Meta:
        # ! unique_together для того чтобы уникальность была для отдельного пользователя 
        # ! (у одного пользователя не может быть проектов с одинаковыми названиями)
        # unique_together = 'autor', 'slug'
        # ! Отображение в базе данных
        verbose_name = 'проект'
        verbose_name_plural = 'Проекты'


class Profile(models.Model):
    """Модель профиля пользователя"""
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="profile", default=None, null=True)
    name = models.CharField("Имя", max_length=100, default="User", null=True, blank=True)
    telegram = models.CharField("Телеграм", max_length=50, blank=True, null=True, default="")
    register_date = models.DateField(default=localdate)
    photo = models.ImageField("Фото профиля", null=True, blank=True, upload_to="usersphotos/", 
                              default='usersphotos/default.png')
    age = models.IntegerField("Возраст", default=18)
    organization = models.CharField("Организация", max_length=100,
                                     default="Самозанятый")
    followers = models.ManyToManyField(User, related_name='following')
    notifications = models.ManyToManyField(Notification)
    is_check_notification = models.BooleanField("Чтение комментариев", default=True)
    achievements = models.ManyToManyField(Achievement)
    
    # liked_projects = models.ManyToManyField(Project, related_name="likedprojects")

    def __str__(self):
        return self.user.username
    
    class Meta:
        verbose_name = 'профиль'
        verbose_name_plural = 'Профили'
    
    def is_friend(self, other: User):
        other_followers = Profile.objects.get(user=other).followers.all()
        if other in self.followers.all() and self.user in other_followers:
            return True
        return False

    def is_follower(self, other: User):
        if other in self.followers.all():
            return True
        return False


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance, name=instance.username)

mysite/templates/project/create_project.html
{% extends 'base.html' %}

{% load static %}

{% block title %}PicHub{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/create_project.css' %}">

    <!-- Подключаем dropzone -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.9.2/dropzone.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.9.2/dropzone.min.js"></script>
    <!-- <script src="https://unpkg.com/dropzone@6.0.0-beta.1/dist/dropzone-min.js"></script>
    <link href="https://unpkg.com/dropzone@6.0.0-beta.1/dist/dropzone.css" rel="stylesheet" type="text/css" />
    <script src="{% static 'js/changedropzone.js' %}"></script> -->
{% endblock %}

{% block content %}
<main>
    <section class="top-text">
        <h2>Cоздать новый проект</h2>
        <hr>
    </section>
    {% if projectform.non_field_errors %}
        {% for error in projectform.non_field_errors %}
            <p class="wrong_text">{{ error }}</p>
        {% endfor %}
    {% endif %}
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}    
        <section class="main-information">
            <article class="user-and-name">
                <div>
                    <p>Владелец</p>
                    <div class="fon-input">
                        <p>{{ user.username }}</p>
                    </div>
                </div>
                <h3>/</h3>
                <div>
                    <p>Название проекта</p>
                    <div class="fon-input">
                        {{ projectform.name }}
                    </div>
                </div>
            </article>

            <article class="description">
                <p>Описание(необязательно)</p>
                <div class="fon-input">
                    {{ projectform.description }}
                </div>
            </article>
        </section>
        <hr>
        <section class="radio-input">
            <div>
                {{ projectform.is_private }}
            </div>
            <div>
                <div class="privat">
                    
                    <label>
                        <h3>Публично <img src="{% static 'img/site_img/create_project/book.png' %}" alt=""></h3>
                        <p>Любой в интернете может увидеть этот проект</p>
                    </label>
                </div>

                <div>
                    {% comment %} {{ projectform.is_private['1'] }} {% endcomment %}
                    <label>
                        <h3>Приватно <img src="{% static 'img/site_img/create_project/lock.png' %}" alt=""></h3>
                        <p>Вы выбираете кто может видеть и редактировать этот проект</p>
                    </label>
                </div>
            </div>
        </section>
        <hr>
        <p class="sucsess_text none">Файлы успешно добавлены!</p>
        <div class="add_files">
            <p class="add_files_p">Добавьте файлы</p>
            {{ projectform.files }}
        </div>
        <div class="uploaded_files" id="uploaded_files">
            {% include "blocks/photo_upload_block.html" %}
        </div>
        
        <section class="but">
            <input type="submit" value="Отправить"></input>
        </section>
    </form>
    <script>
        // Появление текста об успешном добавлении файлов 
        $("#id_files").change(() => {
            $(".sucsess_text").removeClass("none");
        });
    </script>
    <script>
        // Dropzone.options.myDropzone = {
        //     maxFilesize: 5, // MB
        //     acceptedFiles: 'image/*',
            // success: function (file, response) {
            //     var imgContainer = document.createElement('div');
            //     imgContainer.className = 'img-container'    ;
            //     imgContainer.innerHTML = '<img src="' + response.file_url + '" alt="Uploaded Image">';
            //     document.getElementById('imagePreview').appendChild(imgContainer);
            // },
            // error: function (file, response) {
            //     alert('Error uploading file: ' + response);
            // }
        // };
    </script>
</main>

<!-- <script src="{% static 'js/dropzone.js' %}"></script> -->
<script src="{% static 'js/setcheck.js' %}"></script>

{% endblock %}

mysite/templates/project/project_files.html
{% extends 'base.html' %}

{% load static %}

{% block title %}PicHub{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/project/project_files.css' %}">
    <link rel="stylesheet" href="{% static 'css/project/header_project.css' %}">
    <link rel="stylesheet" href="{% static 'css/project/project.css' %}">
    <!-- Подключаем fancy-box -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css" />
{% endblock %}

{% block modals_window %}
    <div class="confirm_delete_block" id="confirm_block">
        <a class="close_confirm" id="close_confirm_btn"><i class="fa-solid fa-xmark"></i></a>
        <h3>Вы точно хотите удалить файл?</h3>
        <img src="" alt="" id="delete_img">
        <h3>Для удаления файла впишите в поле <span class="projname">delete</span></h3>
        <p id="error_text"></p>
        <form>
            <input type="text" name="" id="confirm_text">
            <a id="confirm_delete_file_btn">Удалить</a>
        </form>
    </div>
{% endblock %}

{% block content %}
<main>
    <div class="project_info">
        <div class="projname">
            <a href="{% url 'profile' project.autor.username %}">
                <img src="/media/{{ project.autor.profile.photo }}" alt="">
            </a>

            <h2 class="project_autor">{{ project.autor.username }}</h2>
            <h2>/</h2>
            <h2 class="project_name">{{ project.name }}</h2>

            <p class="status">
                {% if project.is_private %}
                    <i class="fa-solid fa-lock"></i> приватный
                {% else %}
                    <i class="fa-solid fa-unlock"></i> публичный
                {% endif %}
            </p>
        </div>
    </div>
    <div class="project_nav">
        {% comment %} href="{% url 'project' project.autor.username project.name %}" {% endcomment %}
        <a class="project_link" href="{% url 'project' project.autor.username project.name %}"><i class="fa-solid fa-images"></i> Проект</a>
        <a class="{% if project.autor == request.user or user.is_superuser %} files_link {% else %} files_end_link {% endif %} current_nav"><i class="fa-solid fa-file"></i> Файлы</a>
        {% if project.autor == request.user or user.is_superuser %}
            <a href="{% url 'settings_proj' project.autor.username project.name %}" class="settings_link"><i class="fa-solid fa-gears"></i> Настройки</a>
        {% endif %}
        <a class="last_nav"></a>
    </div>
    <div class="project_files_block {% if user == project.autor or user.is_superuser %} super_files {% else %} fls {% endif %}">
        <p id="all_error"></p>
        <div class="files_header">
            <p class="photo">Вид</p>
            <p class="center_header">Имя файла</p>
            <p class="date">Дата добавления</p>
            {% if user == project.autor or user.is_superuser %}
            <i class="fa-solid fa-trash"></i>
            <i class="fa-solid fa-star"></i>
            {% endif %}
            <i class="fa-solid fa-download"></i>
        </div>
        {% for file in project.files.all %}
        <div class="img_block">
            <a href="/media/{{ file.file }}" data-fancybox="gallery" class="img_view">
                <img src="/media/{{ file.file }}"> 
            </a>
            <a href="/media/{{ file.file }}" class="filename" target="_blank">{{ file.file }}</a>            
            <p>{{ file.uploaded_at }}</p>
            {% if user == project.autor or user.is_superuser %}
            <!-- Кнопка удаления файла -->
            <a class="delete_file_btn" 
               data-id="{{ file.id }}"
               id="file_del_{{ file.id }}"
               data-csrf="{{ csrf_token }}"
               data-img="/media/{{ file.file }}"><i class="fa-solid fa-trash"></i></a>
            <!-- Кнопка выбора основного файла -->
            <div class="radio_block"><span class="radio"><span class=""></span></span></div>
            {% endif %}

            <a href="/media/{{ file.file }}" download="" class="img_down"><i class="fa-solid fa-download"></i></a>
        </div>
        {% endfor %}
    </div>
    <script src="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js"></script>
    <!-- Скрипты для ajax запросов -->
    {% if user == project.autor or user.is_superuser %}
        <script>
            $(document).ready(function() {
                var main = document.getElementById("main");
                const close_confirm_btn = document.getElementById("close_confirm_btn");
                const confirm_block = document.getElementById("confirm_block");
                const delete_img = document.getElementById("delete_img");
                var id = 0;

                // Подключаение интерфейсных функций
                main.addEventListener('click', () => {
                    main.style.opacity = "1.0";
                    confirm_block.style.display = "none";
                    $("#confirm_text").val('');
                    // Удаляем ошибку на всякий случай
                    error_p = document.getElementById("error_text");
                    error_p.setAttribute("class", "");
                    error_p.innerText = "";
                }, true);
                
                close_confirm_btn.addEventListener("click", () => {
                    main.style.opacity = "1.0";
                    confirm_block.style.display = "none";
                });

                // Обработка открытия поля подтверждения файла
                $('.delete_file_btn').on("click", function(event){
                    event.preventDefault();
                    // Отображаем окно подтверждения
                    main.style.opacity = "0.3";
                    confirm_block.style.display = "flex";
                    confirm_delete_file_btn.setAttribute("data-id", $(this).data("id"));
                    id = $(this).data("id");
                    confirm_delete_file_btn.setAttribute("data-csrf", $(this).data("csrf"));
                    delete_img.setAttribute("src", $(this).data("img"))
                });

                // Обработка удаления файлов
                $('#confirm_delete_file_btn').on("click", function(){
                    event.preventDefault();
                    // получаем текст подтверждения
                    text = $("#confirm_text").val()
                    // Если введено корректное подтвержение иначе Отображаем ошибку
                    if (text == "delete") {
                        $.ajax({
                            url: "/delete_file/",
                            type: "POST",
                            data: {
                                'id': id,
                                'proj': {{ project.id }},
                                'csrfmiddlewaretoken': $("#confirm_delete_file_btn").data("csrf"),
                            },
                            success: function(response) {
                                // Обнуляем значение вводимого поля
                                $("#confirm_text").val('')
                                if (response.result == true){
                                    // Удаляем со страницы запись файла если успешное Удаление
                                    main.style.opacity = "1.0";
                                    confirm_block.style.display = "none";
                                    $("#file_del_" + id).parent().remove()
                                } else {
                                    // Оповещаем об ошибке если остался один файл
                                    const all_error = document.getElementById("all_error");
                                    main.style.opacity = "1.0";
                                    confirm_block.style.display = "none";
                                    all_error.classList = "wrong_text"
                                    all_error.innerText = "В проекте не может быть меньше одного файла!"
                                    
                                    // По истечении 3 секунд убераем уведомление
                                    setTimeout(function(){
                                        all_error.classList = "";
                                        all_error.innerText = "";
                                    }, 5000);
                                }
                            },
                        });
                        // Удаляем ошибку на всякий случай
                        error_p = document.getElementById("error_text");
                        error_p.setAttribute("class", "");
                        error_p.innerText = "";
                    } else {
                        error_p = document.getElementById("error_text");
                        error_p.setAttribute("class", "wrong_text")
                        error_p.innerText = "Некорректный ввод";
                    }
                });
            });
        </script>
    {% endif %}
</main>
{% endblock %}

mysite/templates/project/project_settings.html
{% extends 'base.html' %}

{% load static %}

{% block title %}PicHub{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/project/project.css' %}">
    <link rel="stylesheet" href="{% static 'css/project/project_settings.css' %}">
    <link rel="stylesheet" href="{% static 'css/project/header_project.css' %}">
    <link rel="stylesheet" href="{% static 'css/project/project_settings_edit.css' %}">
    <link rel="stylesheet" href="{% static 'css/project/project_settings_delete.css' %}">
    <link rel="stylesheet" href="{% static 'css/project/project_settings_addfiles.css' %}">
{% endblock %}

{% block content %} 
<main>
    <div class="project_info">
        <div class="projname">
            <a href="{% url 'profile' project.autor.username %}">
                <img src="/media/{{ project.autor.profile.photo }}" alt="">
            </a>
            <h2 class="project_autor">{{ project.autor.username }}</h2>
            <h2>/</h2>
            <h2 class="project_name">{{ project.name }}</h2>
            <p class="status">
                {% if project.is_private %}
                <i class="fa-solid fa-lock"></i> приватный 
                {% else %}
                <i class="fa-solid fa-unlock"></i> публичный 
                {% endif %}
            </p>
        </div>
    </div>
    <div class="project_nav">
        <a class="project_link" href="{% url 'project' project.autor.username project.name %}"><i class="fa-solid fa-images"></i> Проект</a>
        <a href="{% url 'project_files' project.autor.username project.name %}" class="{% if project.autor == request.user or user.is_superuser %} files_link {% else %} files_end_link {% endif %}"><i class="fa-solid fa-file"></i> Файлы</a>
        {% if project.autor == request.user or user.is_superuser %}
            <a class="current_nav settings_link"><i class="fa-solid fa-gears"></i> Настройки</a>
        {% endif %}
        <a class="last_nav"></a>
    </div>
    {% block settings %}
    
    {% endblock %}
</main>
{% endblock %}

mysite/templates/project/project_settings_addfiles.html
{% extends "project/project_settings.html" %}

{% load static %}

{% block settings %}
    <div class="settings_block">
        <div class="settings_nav">
            <a href="{% url 'settings_proj' project.autor.username project.name %}">
                <i class="fa-solid fa-pen-to-square"></i> Изменение
            </a>
            <a href="" class="current_settings_nav">
                <i class="fa-solid fa-file-circle-plus"></i> Добавление файлов
            </a>
            <a href="{% url 'settings_proj_delete' project.autor.username project.name %}">
                <i class="fa-solid fa-trash"></i> Удаление
            </a>
        </div>
        <div class="settings_body">
            <h3>Добавление файлов в проект:</h3>
            <p class="sucsess_text none">Файлы успешно добавлены!</p>
            <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ add_files_form.files }}
                <input type="submit">   
            </form>
        </div>
    </div>
    <script>
        // Появление текста об успешном добавлении файлов 
        $("#id_files").change(() => {
            $(".sucsess_text").removeClass("none");
        });
    </script>
{% endblock %}

mysite/templates/project/project_settings_delete.html
{% extends "project/project_settings.html" %}

{% load static %}

{% block modals_window %}
    <div class="confirm_delete_block" id="confirm_block">
        <a class="close_confirm" id="close_confirm_btn"><i class="fa-solid fa-xmark"></i></a>
        <h3>Вы точно хотите удалить проект <span class="projname">{{ project.name }}</span>? Для удаления проекта впишите в поле <span class="projname">"{{ project.name }}"</span></h3>
        {% if confirm_form.non_field_errors %}
            {% for error in confirm_form.non_field_errors %}
                <p class="wrong_text">{{ error }}</p>
            {% endfor %}
        {% endif %}
        <form method="POST">
            {% csrf_token %}
            {{ confirm_form.projectname }}
            <input type="submit" value="Удалить">
        </form>
    </div>
    <style>
        {% if confirm_form.non_field_errors %}
        .main{
            opacity: 0.3;
        }
        .confirm_delete_block{
            display: flex;
        }
        {% endif %}
    </style>
{% endblock %}

{% block settings %}
    <div class="settings_block">
        <div class="settings_nav">
            <a href="{% url 'settings_proj' project.autor.username project.name %}">
                <i class="fa-solid fa-pen-to-square"></i> Изменение
            </a>
            <a href="{% url 'settings_proj_addfiles' project.autor.username project.name %}">
                <i class="fa-solid fa-file-circle-plus"></i> Добавление файлов
            </a>
            <a href="" class="current_settings_nav">
                <i class="fa-solid fa-trash"></i> Удаление
            </a>
        </div>
        <div class="settings_body">
            <h3>Удаление проекта:</h3>
            <p class="wrong_text">Удалив проект, вы не сможете его восстановить!</p>
            <a id="delete_project_btn" class="del_btn"><i class="fa-solid fa-trash"></i> Удалить</a>
        </div>
    </div>
    <script src="{% static 'js/confirm_delete_show.js' %}"></script>
{% endblock %}